### ISSUE TITLE
Deploy site through action failed

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/data-donuts#129]
I tried running the [Deploy Jekyll site to Pages](https://github.com/compilerla/data-donuts/actions/runs/10638711076) in Github Actions, and it output that it failed. We use this action to ensure old events are removed from the upcoming section on the datadonuts.la website. It also failed when I merged in the last PR to update the footer.

![Screenshot 2024-09-05 at 3 37 50 PM](https://github.com/user-attachments/assets/2bf6c349-077f-4f76-b847-3e2cc59502c6)

**Comment by angela-tran** [comment]
I see in the Settings for this repo that GitHub Pages is disabled, which is why the workflow is failing. I think it'd be best to wait for @thekaveman to be back online and ask him for more context on why it's currently disabled.

**Comment by thekaveman** [comment]
Ah... so a couple weeks ago when GitHub went down, we swapped the hosting of this site from GitHub pages to Netlify (I thought I had already done this, but apparently not).

Netlify has its own integration with GitHub and it is handling the deploy now, based on merges to `main`. E.g. the footer update in #127 is live because Netlify deployed that change.

But I forgot about this use case of manually running the deploy to clear out the old event. So we just need a new workflow that triggers the Netlify deploy using their CLI tool.

**Comment by thekaveman** [comment]
#113 is in-progress and will fix this
